[package]
name = "lotto"
version = "0.1.0"
description = "Created with Anchor"
edition.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib", "lib"]
name = "lotto"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build"]
anchor-debug = []
custom-heap = []
custom-panic = []
localnet = []
devnet = []
test-fast = []


[dependencies]
anchor-lang = { version = "=1.1.2", features = ["init-if-needed"] }
ephemeral-vrf-sdk = { version = "=0.17.0", default-features = false, features = ["anchor"] }
solana-sha256-hasher = "=3.1.0"


[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("solana"))'] }
